### ISSUE TITLE
"Fatal Error: 'Uncaught Error: Class 'Culqi\\Culqi' not found in 

### ISSUE THREAD

**Issue by impunkj** [jludena/Culqi#1]
Hello Thanks for your module, 

But when i try to do payment i get error 

ASCII text, with very long lines, with no line terminators
"Fatal Error: 'Uncaught Error: Class 'Culqi\\Culqi' not found in \/home\/tvila040\/public_html\/new\/app\/code\/Culqi\/Native\/Model\/Payment.php:104\nStack trace:\n#0 \/home\/tvila040\/public_html\/new\/generated\/code\/Culqi\/Native\/Model\/Payment\/Interceptor.php(24): Culqi\\Native\\Model\\Payment->capture(Object(Magento\\Sales\\Model\\Order\\Payment\\Interceptor), '105')\n#1 \/home\/tvila040\/public_html\/new\/vendor\/magento\/module-sales\/Model\/Order\/Payment\/Operations\/CaptureOperation.php(82): 

Can you please let me know if i missing something

Thanks

**Comment by devfiis** [comment]
Hi Pankaj, I am sorry for the delay.

Make sure that your project magento has added in the composer.json the
Culqi SDK

"culqi/culqi-php": "1.3.3"
--------------------------------------------
https://github.com/culqi/culqi-php

Regards,
Jludena

**Comment by impunkj** [comment]
Hello,
yes thanks for your reply
I solved that issues
I forget to install culqi-php

One more thing if you can answer 
All the details is enter and also order is showing in payment gateway
But in first call getting error payment capture error.

When check log i found this issues 


{"object": "error", "type": "parameter_error", "merchant_message": "The field 'source_id' is invalid or empty.", "param": "source_id"} [] []

If you have idea about this

Thanks & Regards
Impunkj

**Comment by devfiis** [comment]
Hi Impunkj,
From frontend, a direct "authorization" to Culqi is made and a token is returned (var token = Culqi.token.id;), the token is sent to the backend to finish the operation.

The token is the resource_id.
This is the documentation that guides me
https://www.culqi.com/docs/#/pagos/js

Regards,
Jludena
